os: osx
language: dart
dart:
  - stable

before_install:
  - brew update
  - brew install lcov

dart_task:
  - test: --platform vm
  - dartanalyzer: --fatal-warnings lib
  - dartfmt

script: 
  # Collect coverage and psot to codecov
  - bash dart --pause-isolates-on-exit --disable-service-auth-codes --enable-vm-service=9090 test/unit/kotlin_extensions_test.dart
  - bash collect_coverage --uri=http://127.0.0.1:9090/ -o coverage.json --resume-isolates
  - bash format_coverage -l -i coverage.json -o lcov.info --packages=.packages --report-on=lib
  - bash <(curl -s https://codecov.io/bash)
