name: kotlin_extensions
version: 0.0.1
description: A library of extension method implementations inspired by Kotlin.

# TODO: Update these
homepage: https://github.com/danchurch-wk/KotlinExtensionsForDart
repository: https://github.com/danchurch-wk/KotlinExtensionsForDart

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  meta: ^1.0.0

dev_dependencies:
  test: ^1.0.0
  pedantic: ^1.9.0
